# Generated by Django 5.0.7 on 2024-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_images', verbose_name='Product image')),
                ('name', models.CharField(max_length=60, verbose_name='Product name')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
            ],
        ),
    ]
